#!/usr/bin/env php

<?php

use HtmlDownload\DownloadLinksCommand;
use Symfony\Component\Console\Application;

require 'vendor/autoload.php';

$app = new Application('HTML Download', '1.0');
$app->add(new DownloadLinksCommand);
$app->run();