#!/usr/bin/env php

<?php

use HtmlDownload\DownloadList;
use Symfony\Component\Console\Application;

require 'vendor/autoload.php';

$app = new Application('HTML Download', '1.0');
$app->add(new DownloadList);
$app->run();